node_name: "ExinPool"
service_name: "ChainX"
log_file: "chainx_blocks.log"
webhook:
  webhook_url: "https://webhook.exinwork.com/api/send?access_token={}"
  access_token: ""
node:
  api_url: "http://api.mixinwallet.com/getinfo?node="
  node_tag: ""
  local_node: ""
  remote_node_1: "wss://ws.chainxtools.com"
  remote_node_2: "wss://chainx.maiziqianbao.net/ws"
mail:
  sender: ""
  password: ""
  receiver: ""
  subject: "ChainX Monitor"
  smtp_url: "smtp.exmail.qq.com"
  smtp_port: 465